node1:
  expose:
    - "8083"
  ports:
    - "8083:8083"
  image: ernespn/fsharp-calculator
 
node2:
  expose:
    - "8084"
  ports:
    - "8084:8084"
  image: ernespn/python-calculator
  
node3:
  expose:
    - "8085"
  ports:
    - "8085:8085"
  tty: true
  image: ernespn/csharp-calculator
  links:
   - mongodb

node4:
  expose:
    - "8082"
  ports:
    - "8082:8082"
  image: ernespn/nodejs-calculator
  links:
   - mongodb
  
node5:
  expose:
    - "8081"
  ports:
    - "8081:8081"
  image: ernespn/spring-services
  links:
   - mongodb
  
website:
  expose:
    - "9000"
  ports:
    - "9000:9000"
  image: ernespn/personal-website
  
mongodb:
  expose:
   - "27017"
  ports:
  - "27017:27017"
  image: mongo:3.3.15
  
nginx:
  links:
   - node1
   - node2
   - node3
   - node4
   - node5
   - website
  image: ernespn/lb-nginx
  ports:
   - "8080:8080"
   - "80:80"
  expose:
   - "8080"
   - "80"